---
title: "Toronto Homicides"
author: "Tim Chisamore"
date: "`r format(Sys.Date())`"
output: html_document
---

# 1 Introduction

The Toronto Police Service (TPS) provides data on homicides, shootings, and major crime indicators (MCI), among other things, through the Public Safety Data Portal.

I was interested in exploring homicides in Toronto through time and space using a variety of methods. 

# 2 Methods



# 3 Results

```{r setup, include=FALSE}

knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	fig.width = 12,
	fig.height = 8
)

source(here::here("requirements.R"))

list_of_functions <- list.files(here::here("src", "functions"))

list_of_functions <-
	here::here("src", "functions", list_of_functions)

walk(list_of_functions, source)

```

```{r api_call, include=FALSE}

toronto_homicides <- api_call()

```

```{r cleaaning_data, include=FALSE}

toronto_homicides_cleaned <- cleaning_data(toronto_homicides)

```

```{r formatting_data, include=FALSE}

toronto_homicides_cleaned_formatted <-
	formatting_data(toronto_homicides_cleaned)

```

```{r homicides_by_year_and_type}

homicides_by_year_and_type(toronto_homicides_cleaned_formatted)

```

```{r homicides_by_day_and_type}

homicides_by_day_and_type(toronto_homicides_cleaned_formatted)

```

```{r homicides_by_day_and_year}

homicides_by_day_and_year(toronto_homicides_cleaned_formatted)

```

```{r homicide_surveillance_by_yearmonth}

homicide_surveillance_by_yearmonth(toronto_homicides_cleaned_formatted)

```

# 4 Discussion